import csv
from googlesearch import search

# List of company names
companies = [
   "Belux Comptafisc Sarl",
    "Benoy Kartheiser Management S.à r.l.",
    "Berenberg Joh. Berenberg, Gossler & Co. KG",
    "Bergos AG",
    "Berkeley Energy Limited",
    "Berlin-Chemie AG",
    "Berner Kantonalbank AG",
    "BFC Consulting SPRL",
    "BFM Experts SAM",
    "BfV Bank für Vermögen AG",
    "Bienen & Wilms Beratungsgesellschaft mbH",
    "Bi-Invest Endowment Management S.à.r.l",
    "BinckBank",
    "Birdee",
    "BKW Management AG",
    "Blackfort Capital AG",
    "BlackPoint Asset Management GmbH",
    "BLUEGEM CAPITAL PARTNERS",
    "BNP Paribas S.A. Niederlassung Deutschland - Consorsbank by BNP Paribas",
    "BNP Paribas S.A. Niederlassung Deutschland - Corporate & Institutional Banking",
    "Bonacapital Family Office S.A.",
    "Bond Capital House GmbH",
    "BOV Asset Management Ltd.",
    "BOV Fund Services Limited",
    "Bovemij",
    "Bow Trustee Ltd (ex:Intelligentsia Limited)",
    "BPD Immobilienentwicklung GmbH",
    "BPD Ontwikkeling BV",
    "Brandkontoret AB",
    "Bremer Family Office AG",
    "BTG Pactual Europe SA",
    "Bul Ins",
    "Bulgaria Insurance AD",
    "Buruj Insurance",
    "Bustelberg Effectenkantoor B.V.",
    "BV Bayerische Vermögen GmbH",
    "BVV Pension Management GmbH",
    "BY die Bayerische Vorsorge Lebensversicherung a.G.",
    "C&D Associés S.à r.l.",
    "Cabinet Bruno Willy SCHROEDER",
    "Cabinet Brych François Jean",
    "Cabinet Comptable Yvan BELAIEFF",
    "Cabinet Delphine Brych",
    "Cabinet Frank Morel",
    "Cabinet Pascale Taramazzo",
    "Cabinet Paul Stefanelli",
    "Cabinet Rastello-Carmona Janick",
    "Cabinet Sabine Steiner Toesca",
    "Cabinet Viale",
    "CAIBUO CAPITAL S.A R.L.",
    "Calista Direct Investors SA",
    "Canada Life Assurance Europe PLC",
    "Canada Life Assurance Europe plc Niederlassung für Deutschland",
    "CAP Consultants International S.à r.l.",
    "Capelli Lux SA",
    "Capgemini Nederland B.V.",
    "Capital Bank",
    "Card Prepaid Limited trading as Bankable",
    "CATAM Asset Management AG",
    "CBRE (Global Investment Administration)",
    "CCA Life Settlements SARL",
    "CCB Life",
    "CCP Financial Consultants Ltd.- Chestnut",
    "Centrale Hypotheekbank NV- LN CW",
    "CENTRIS CAPITAL AG",
    "Centry Global Group",
    "CentryGlobal",
    "Centup SA",
    "CGE Sàrl - Centre Général d'Expertises Comptables Sàrl",
    "Chester & Jones Sàrl",
    "Chestnut BVI Limited",
    "China Taiping Insurance (UK) Co Ltd",
    "CHS Alliance",
    "CIG Pannónia Biztosító",
    "Cilia Formosa Financial Advisors",
    "Circular IT holdings",
    "Circumference FS (Luxembourg) S.A.",
    "Citadel Insurance plc",
    "Citco C&T Holdings (Luxembourg) S.à r.l.",
    "Citibank, N.A., London Branch",
    "Citizen Lane Ltd",
    "Clearhaus A/S",
    "Clearsky Solutions Limited",
    "Clientis AG",
    "Clive Caruana (k/a CCPS Malta)",
    "Codur S.A.",
    "Coetzee and Partners Ltd.",
    "Cofimo SAM",
    "Coin Meester B.V.- LN NL",
    "Colin&Cie. Schweiz AG",
    "Colin&Cie. Luxembourg S.A.",
    "Columbus Venture Partners",
    "Columna Capital Luxembourg S.à r.l.",
    "Commerz Real AG",
    "Commissariat aux Assurances",
    "Compagnie Financière Indépendante S.A",
    "Compagnie lmmobilière de Belgique SA (IMMOBEL)",
    "Companyweb",
    "Comptassist SA",
    "Comptaxiome S.à.r.l.",
    "Compulsory insurance Centre",
    "Concentrix KYC Services (ex:Green Point SAS > Webhelp)",
    "CONCEPT Vermögensmanagement GmbH & Co. KG",
    "Condor Allgemeine Versicherungs-Aktiengesellschaft",
    "Confiancia Luxemburg Sàrl",
    "Confiancia St. Vith GmbH",
    "CONREN Fortune S.A.",
    "Conservatrix N.V.",
    "Contact Advisory Services Limited (Kyte Consultants)",
    "Convera Europe Financial SA",
    "Convera UK Financial Ltd",
    "CONVOTIS (Luxembourg) PSF S.A (Ex: Calligo)",
    "Cornèr Banca SA",
    "CREALOGIX (Deutschland) GmbH",
    "Credit Oman SAOC",
    "Credit Suisse AG",
    "CreditDevice",
    "Creditreform Luxembourg S.A.",
    "Crescendo Services (Lux) S.à r.l.",
    "Crestbridge SA",
    "Croatia osiguranje d.d.",
    "CS Expertise Sàrl",
    "CSB International Limited",
    "Curalia AAM",
    "D.O.R.C. (Dutch ophtalmic research center)",
    "D2M SARL",
    "Dallbogg",
    "DAM - Diversified Asset Management S.A.",
    "Dammers Shipmanagement N.V.",
    "Danieli Finance Solutions S.A.",
    "Dansk Sundhedssikring",
    "DAS Netherlands",
    "DCA SAM - Diagnostic Comptabilité Audit",
    "De Pury Pictet Turrettini SA (PPT Belgium)",
    "de Volksbank N.V",
    "DekaBank Deutsche Girozentrale",
    "Delos Business Information Ltd-LN CY",
    "DEMAK Finanzdienstleistungen e.K.",
    "Deutsche Apotheker- und Ärztebank eG",
    "Deutsche Bank (Schweiz) AG",
    "Deutsche Bank (Suisse) SA",
    "Deutsche Rückversicherung AG",
    "Deutscher Pensionsfonds AG",
    "DFM N.V.",
    "Dhofar Insurance Company",
    "Die Bayerische Versicherung",
    "DJE Kapital AG",
    "DKV Luxembourg SA (Linked to LaLuxVie)",
    "DLT Securities GmbH",
    "Domos FS Ltd",
    "Dowdall (ZH) Limited (ex Michael Mercieca contract)",
    "Dr Francesca Portelli",
    "Dr. Larry J. Gauci",
    "Dr. Malcolm Licari B.A. LL.D.",
    "Dr. Michaela Millo",
    "Dr. Tiziana Micallef",
    "Duro & Partners",
    "DZ PRIVATBANK S.A.",
    "E audits",
    "E.O.C.",
    "Eagle Wealth Management",
    "Eagle Wealth Management (Mauritius) Ltd",
    "EASE SA",
    "Eazyinsure",
    "EB - Sustainable Investment Management GmbH",
    "Edmond de Rothschild (Europe) SA",
    "Edmond de Rothschild (Suisse) S.A.",
    "Edmond Halley Pensioenmanagement",
    "EFG Bank AG",
    "eGroup Europe SA",
    "Eika Forsikring AS",
    "Eika Gruppen AS (Eika Bank)",
    "Elastofirm",
    "Emerald Wealth Partners AG",
    "EnBW mobility + AG & Co. KG",
    "Engelwood Fund & Corporate Services S.A.",
    "Entrust Revision S.a.r.l",
    "Eqonex Investment Products S.à.r.l.",
    "Equiom",
    "Equiom Consultants S.à r.l.",
    "ERGO Group AG",
    "ERGO Insurance N.V.",
    "ERGO Life S.A.",
    "Grand Total"
]

# Function to get top search result for a company
def get_google_domain(company_name):
    query = f"{company_name} official site"
    try:
        for result in search(query, num_results=1):
            return result
    except Exception as e:
        return f"Error: {e}"

# Write to CSV
with open("company_domains.csv", mode="w", newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Company Name", "Domain"])

    for company in companies:
        domain = get_google_domain(company)
        print(f"{company}: {domain}")
        writer.writerow([company, domain])
